<a href="https://colab.research.google.com/github/Nirma-Kushwaha/Computational-Mathematics-workshop/blob/main/Workshop6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem 1: Create a 2D ndarray of type Integer and see its properties.

In [ ]:
"""
This is a script file for Week 5 Workshop.
Author: Nirma Kushwaha
"""
import numpy as np
if __name__ == "__main__":
  """Problem 1: Create a 2D ndarry (Matrix) of type Float,
  e.g, [[1,2.3], [4,5,6],[7,8,9]]
  and see its properties/attributes """
  arr = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=float)
  print("Array =")
  print(arr)
  print("Data Type of the Arrapy                    =", arr.dtype)
  print("Number of dimensions of the Array          =", arr.ndim)
  print("Shape of the Array                         =", arr.shape)
  print("Size of the Array                          =", arr.size)
  print("Number of the bytes used by each element of the Array =", arr.itemsize)
  print("Total bytes used by the Array              =", arr.nbytes)
  print("Memory Layout information                  =", arr.flags)

Array =
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Data Type of the Arrapy                    = float64
Number of dimensions of the Array          = 2
Shape of the Array                         = (3, 3)
Size of the Array                          = 9
Number of the bytes used by each element of the Array = 8
Total bytes used by the Array              = 72
Memory Layout information                  =   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



Problem 2: Create a 2D ndarray (matrix) of shape (4,5) with all elements equal to 3.0 and print
the matrix.

In [ ]:
"""Problem 2: Create a 2D ndarray (Matrix) of shape (4,5) with all elements equal to 3.0 and print the matrix."""
arr2 = 3 * np.ones((4,5), dtype=float)
print("Array = ")
print(arr2)
print("Shape = ", arr2.shape)
print("DataType = ", arr2.dtype)

Array = 
[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]
Shape =  (4, 5)
DataType =  float64


Problem 3: What is the other way to create the same matrix as above?

In [ ]:
import numpy as np
arr2 = np.zeros((4,5)) + 3.0
print("Array = ")
print(arr2)
print("Shape = ", arr2.shape)
print("DataType = ", arr2.dtype)

Array = 
[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]
Shape =  (4, 5)
DataType =  float64


Problem 4: Construct a matrix �𝑎𝑎𝑖𝑖𝑖𝑖 � of shape (3,3) whose elements are given by 𝑎𝑎𝑖𝑖𝑖𝑖 = 1
2 |𝑖𝑖 − 3𝑗𝑗.

In [ ]:
"""Problem 4: Construct a matrix [a_ij] of shape(3,3) whose elements are given by a_ij=1/2 /i-3j/.
This is the same question in the lecture slide."""
#Note: in Python indexing starts at 0
arr4 = np.fromfunction(lambda i, j: np.abs(i+1-3*(j+1))/2, (3,3), dtype=int)
print("Array = ")
print(arr4)
print("Shape = ", arr4.shape)
print("DataType = ", arr4.dtype)

Array = 
[[1.  2.5 4. ]
 [0.5 2.  3.5]
 [0.  1.5 3. ]]
Shape =  (3, 3)
DataType =  float64


Problem 5: Construct a diagonal matrix of shape (4,4) whose diagonal elements are [1,2,3,4].

In [ ]:
import numpy as np
arr = np.diag([1,2,3,4])
print("Diagonal Matrix = ")
print(arr)
print("Shape = ", arr.shape)
print("DataType = ", arr.dtype)

Diagonal Matrix = 
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
Shape =  (4, 4)
DataType =  int64


Problem 6: Construct a matrix of shape (4,5) with whatever elements, and then slice it to obtain
a matrix of shape (3,3) that contains only upper-left portion of the original matrix.

In [ ]:
import numpy as np
#Create a (4,5) matrix (any values)
A = np.arange(1,21).reshape(4,5)
print("Original Matrix (4x5):")
print(A)
#Slice upper-left 3x3 portion
B =A[0:3, 0:3]
print("\n Upper-left portion:")
print(B)

Original Matrix (4x5):
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

 Upper-left portion:
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


Part 2: Perform some basic operation on Vectors/Matrices:

Problem 1: Create two matrices 𝑨𝑨 = �
1 2 3
4 5 6
7 8 9
� and 𝑩𝑩 = �1 1 1
2 2 2�. Add them together. What
do you observe? Give the explanation behind it.

In [ ]:
import numpy as np
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
B = np.array([[1,1,1],
              [2,2,2]])
print("Matrix A:")
print(A)
print("Matrix B:")
print(B)
#Try to add
C = A + B
print("A + B = ")
print(C)

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B:
[[1 1 1]
 [2 2 2]]


ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

This code will produce an error.
Matrix A is of shape(3,3) and matrix : B is of shape(2,3). Since matrix addition requires both matrices to have the same dimensions, they cannot be added. Therefore, NumPy gives an error because the number of rows is different.

Problem 2: Given a matrix and a vector, write a Python function that performs Matrix-Vector
product. Check your result with NumPy built-in function to perform Matrix-Vector/Matrix-
Matrix product.

In [ ]:
def dot_product(vec1, vec2):
  #flatten the input vectors
  vec1 = vec1.flatten()
  vec2 = vec2.flatten()
  return np.sum(np.multiply(vec1, vec2))
def matrix_vector_product(mat, vec):
  m,n = mat.shape
  p,q = vec.shape
  assert n==p, "the matrix and vector are not compatible for multiplication!"
  #Create a ndarray to store the result
  result = np.zeros((m,q), dtype=float)
  #Loop to perform Matrix-Vector product
  #Perform dot product between the vector and each row of the matrix
  for i in range(m):
    result[i] = dot_product(mat[i,:], vec)
  return result

if __name__ == "__main__":
    """Part 2: Problem 2: Given a matrix and a vector, write a function that performs Matrix-Vector product."""
    mat1 = np.full((3,3), 3, dtype=int)
    vec1 = np.full((3,1), 2, dtype=int)
    print("Matrix = ")
    print(mat1)
    print("Vector = ")
    print(vec1)
    #Call the function matrix_vector_product(mat, vec)
    result1 = matrix_vector_product(mat1, vec1)
    print("Result = ")
    print(result1)
    #Check with numpy in-built function for multiplication
    result2 = mat1 @ vec1
    print("Result = ")
    print(result2)



Matrix = 
[[3 3 3]
 [3 3 3]
 [3 3 3]]
Vector = 
[[2]
 [2]
 [2]]
Result = 
[[18.]
 [18.]
 [18.]]
Result = 
[[18]
 [18]
 [18]]


Problem 3: Given two compatible matrices, write a Python function that performs Matrix-Matrix
product. Check your result with NumPy built-in function to perform Matrix-Vector/Matrix-
Matrix product.

In [ ]:
import numpy as np

# Function for matrix-matrix multiplication
def matrix_multiply(A, B):
    rows_A, cols_A = A.shape
    rows_B, cols_B = B.shape

    result = np.zeros((rows_A, cols_B))

    for i in range(rows_A):
        for j in range(cols_B):
            for k in range(cols_A):
                result[i][j] += A[i][k] * B[k][j]

    return result


# Compatible matrices
A = np.array([[1,2,3],
              [4,5,6]])

B = np.array([[1,2],
              [3,4],
              [5,6]])

# Using user-defined function
C1 = matrix_multiply(A, B)
print("Manual Result:")
print(C1)

# Using NumPy built-in function
C2 = np.dot(A, B)
print("\nNumpy Result:")
print(C2)

Manual Result:
[[22. 28.]
 [49. 64.]]

Numpy Result:
[[22 28]
 [49 64]]


Problem 4: Given a matrix, write a Python function that checks if it is a symmetric matrix.

In [ ]:
import numpy as np

def is_symmetric(A):
    # matrix must be square
    if A.shape[0] != A.shape[1]:
        return False

    for i in range(A.shape[0]):
        for j in range(A.shape[1]):
            if A[i][j] != A[j][i]:
                return False
    return True


# Example matrix
A = np.array([[1,2,3],
              [2,5,6],
              [3,6,9]])

print("Matrix A:")
print(A)

if is_symmetric(A):
    print("Matrix is Symmetric")
else:
    print("Matrix is Not Symmetric")


Matrix A:
[[1 2 3]
 [2 5 6]
 [3 6 9]]
Matrix is Symmetric
